% creating a home environment 
clc,clf;
h = surf([-2,-2;2,2] ...
,[2,2;2,2] ...
,[0 4; 0 4] ...
,'CData',imread('bedwall.jpg') ...
,'FaceColor','texturemap');

hold on;
h2 = surf([2,2;2,2] ...
,[2,2;-2,-2] ...
,[0 4; 0 4] ...
,'CData',imread('bookwall2.jpeg') ...
,'FaceColor','texturemap');

h3 = surf([-2,-2;2,2] ...
,[-2,2;-2,2] ...
,[0 0; 0 0] ...
,'CData',imread('lightwood.jpg') ...
,'FaceColor','texturemap');

dir = [1 0 0];
dir2 = [0 1 0];

rotate(h2,dir,90);
rotate(h,dir2,90);

table = PlaceObject('newtable2.ply',[-0.6,-0.2,0.1]);

xlabel('X-axis');
ylabel('Y-axis');
zlabel('Z-axis');
