function eStopGUI()
    global estopBtnHandle ResumebtnHandle
    % Create main figure for GUI
    mainFig = figure('Name', 'Control Panel', 'NumberTitle', 'off', 'Position', [100, 100, 500, 200], 'Color', [0.8 0.8 0.8]);


    % Button for "E-Stop"
    estopBtnHandle = uicontrol('Style', 'pushbutton', 'String', 'E-Stop', ...
        'Position', [50, 50, 175, 100], ...
        'Callback', @toggleStop, ...
        'FontSize', 20, ...
        'BackgroundColor', [1, 0.2, 0], ...
        'ForegroundColor', [1 1 1], ...
        'Tag', 'emergency');

    % Resume Button
    ResumebtnHandle = uicontrol('Style', 'pushbutton', 'String', 'Resume', ...
        'Position', [275, 50, 175, 100], ...
        'Callback', @toggleStop, ...
        'FontSize', 20, ...
        'BackgroundColor', [0.2 0.6 0.2], ...
        'ForegroundColor', [1 1 1], ...
        'Tag', 'resume');
end